name: idall_in_app_authentication_example
description: Demonstrates how to use the idall_in_app_authentication plugin.

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  idall_in_app_authentication:
    path: ../
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
