name: idall_in_app_authentication
description: A package to handle authorization with idall based on oAuth2
version: 0.0.11
author: TebyanSmart Dev team
homepage: http://tebyansmart.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  oauth2: ^2.0.0
  url_launcher: ^6.0.4
  shared_preferences: ^2.0.5
  uni_links: ^0.5.1
#  hive: ^2.0.0
  path_provider: ^2.0.1
  http: ^0.13.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.3


flutter:
  plugin:
    platforms:
      android:
        package: com.tebyansmart.idall_in_app_authentication
        pluginClass: IdallInAppAuthenticationPlugin
      ios:
        pluginClass: IdallInAppAuthenticationPlugin

