name: idall_in_app_authentication
description: A package to handle authorization with idall based on oAuth2
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  oauth2: ^1.6.3
  uni_links: ^0.4.0
  rxdart: ^0.24.1
  url_launcher: ^5.7.10
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


